### ISSUE TITLE
emacs in top 5 memory consumers?

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/legacy.httparchive.org#108]
Looking at http://httparchive.org/newrelic-dash/ the top 5 memory consumers consistently include emacs. Forgive my nano-using ignorance, but why would a text editor always be consuming so much memory?

**Comment by pmeenan** [comment]
@stevesouders  usually leaves an emacs session open when he is working on stuff on the server (in a screen session?).  Probably a good idea to close it out if it isn't actively being used.
