### ISSUE TITLE
Consider breaking up the httparchive:runs dataset on BigQuery

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/legacy.httparchive.org#112]
[Context](https://stackoverflow.com/questions/44317723/unrecognized-column-from-wildcard-table)

The [runs dataset](https://bigquery.cloud.google.com/dataset/httparchive:runs) contains pages and requests tables for both desktop and mobile. The difference in schemas between pages and requests means that we can't run wildcard queries over all tables.

Here's what I'm proposing:

- Break up runs into requests and pages datasets. A dataset should have a consistent schema for all of its tables.
- Prefix with desktop/mobile rather than suffix. BQ provides a utility to wildcard a [suffix](https://cloud.google.com/bigquery/docs/querying-wildcard-tables#filtering_selected_tables_using_table_suffix) but not prefix or middle of a table name. Alternatively, if there's value, consider joining both desktop/mobile into a single table with a new "client" index.
- Do not include view tables (latest_pages). This prevents top-level table wildcards like `httparchive.runs.*` because the wildcard would include the views. For whatever reason views in a wildcard result in an error.

This would probably require deprecating and removing the runs dataset and all of the process changes and reeducation surrounding that.

Meanwhile, I can use the workaround to UNION all tables explicitly by name, but that's no fun.

**Comment by rviscomi** [comment]
> For whatever reason views in a wildcard result in an error.

It seems this is because the views are written in legacy SQL and the wildcard query used standard SQL. So in my proposal, I'd amend it to "only use view tables written in standard SQL".

**Comment by igrigorik** [comment]
> Break up runs into requests and pages datasets. A dataset should have a consistent schema for all of its tables.

This seems like an unnecessarily strict requirement. A dataset is a mechanism to group a set of related tables, and the benefit is that this dataset is a single entrypoint that developers can find/share/explore. 

> Do not include view tables (latest_pages). 

But that breaks all the 'latest pages' use cases, which is a valid and popular query.. =/

---

@fhoffa can you chime in on how we can resolve the tension between all of the above?

**Comment by rviscomi** [comment]
Biggest high impact / low effort thing to do would just be to rename the runs tables from `YYYY_MM_DD_table_client` to `table_client_YYYY_MM_DD`. That way we could query for all pages (pages_*), all mobile requests (request_mobile_*), etc.

> this dataset is a single entrypoint that developers can find/share/explore.

Browsing is pretty gnarly when pages/requests are combined and the newer tables are at the bottom. For the same reason why I like the har tables in a separate dataset, I think it would actually facilitate exploration to keep unlike tables grouped separately.

> But that breaks all the 'latest pages' use cases, which is a valid and popular query.. =/

Yeah we can keep them. I amended my position on killing them entirely. We'd just rewrite them in standard SQL. Otherwise we're limited to legacy wildcard queries. That may not be an issue if we reformat the table names, eg `pages_*` won't match views anyway. It's also not clear what value there is in querying for all dated tables plus the latest table, since that's already included in the former. I guess it's just a nice to have to be able to query for all tables under a dataset, but probably not worth the effort.

**Comment by igrigorik** [comment]
> Biggest high impact / low effort thing to do would just be to rename the runs tables from YYYY_MM_DD_table_client to table_client_YYYY_MM_DD. That way we could query for all pages (pages_*), all mobile requests (requests_mobile_*), etc.

Hmm, so the downside to that is that now if you're using the GUI table explorer, the pages and requests tables will be in completely different parts the tree -- switching previews will be a pain. Can't win at this game.. =/

Taking a step back.. These tables are bootstrapped off the MySQL dumps. Our plan is to get rid of MySQL, so.. is this discussion even relevant in medium~long term? 

The simplest answer is no, which means that everyone must then query the HAR tables. That makes life easy for us, but hard and much more expensive for everyone else. My guess is that we do want to extract some summary tables that are easy(er). With that in mind: 

 - I think we should work on the assumption that we'll have to build summary tables from the har tables -- e.g. run some query that picks fields we care about and materializes the results.
 - Which field do we care about? I don't think we should assume that we must have parity with existing tables.
 - Does it make sense to keep pages and requests data as separate? What if we had requests as nested under table records?
 - What other tips / tricks / best practices should we consider to make querying and exploration simpler?

/cc @fhoffa

**Comment by rviscomi** [comment]
I like the idea of taking this opportunity to rethink the data organization. I'll stew in it and let Felipe share his thoughts.

**Comment by Themanwithoutaplan** [comment]
From my perspective a pages table makes a lot of sense. This is the basis for all the website reports and makes sense to have the aggregated data, though the schema should be normalised (I will provide the schema I use on the beta site). The requests table on the other hand is less practical as it essentially just a log, except of completely disparate activities. Depending on the DB there might be some advantage in a requests table for the statistics of a particular run (Postgres has quite a few functions that are currently done in PHP) but I suspect it's probably also pretty easy to do this in BQ.

**Comment by rviscomi** [comment]
Done https://discuss.httparchive.org/t/notice-reorganizing-the-har-and-runs-datasets-on-bigquery/1235
