### ISSUE TITLE
Desktop Data from 2017-01 missing

### ISSUE THREAD

**Issue by Themanwithoutaplan** [HTTPArchive/legacy.httparchive.org#116]
I've needed to reimport some data and it looks like the desktop runs (pages.csv) from 1st and 15th Jan is missing. Can they be recreated?

**Comment by rviscomi** [comment]
I think this is a duplicate of https://github.com/HTTPArchive/httparchive/issues/74

**Comment by Themanwithoutaplan** [comment]
It may be related but it's not a duplicate. The downloads page lists January 2017 but the links are broken. The thing is that the dumps were available at the time and contained valid data. Can they be recreated?

**Comment by rviscomi** [comment]
Combining with #74
