### ISSUE TITLE
Integrate JS parse / execute and code coverage metrics

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/legacy.httparchive.org#124]
@pmeenan are there any other metrics besides the ones below that we can leverage for JS runtime insights?

![image](https://user-images.githubusercontent.com/1120896/28729030-f66a5d9c-7398-11e7-967d-bd139e72d853.png)

**Comment by pmeenan** [comment]
Those are the big ones for V8 parsing.  If we add the v8 runtime stats trace events (disabled-by-default-v8.runtime_stats) we can get more granular details but it adds some overhead.  The _cpu metrics are available both at the top-level as well as on each request so be careful pulling them out to make sure you get the ones you want (and don't double-count).

Code coverage isn't collected yet (still unsure if it is going to be a Lighthouse audit or if WPT should collect it separately).

**Comment by pmeenan** [comment]
There are also all of the TTI metrics if you want insight into how blocked the main thread is (tangentially related):

```
                "_FirstInteractive": 37341,
                "_TimeToInteractive": 37341,
                "_TTIMeasurementEnd": 42418,
                "_LastInteractive": 37341,
```

**Comment by igrigorik** [comment]
@pmeenan what about coverage stats? Are we logging that?

**Comment by addyosmani** [comment]
@pmeenan Just caught up with Patrick H and Paul Irish. It's possible code coverage support for JS could land in Lighthouse this quarter or next. 

One requirement it would have is one more (separate) run, I think taking WebPageTest up to 4-5 in total as Lighthouse itself gets a different run. Unsure if this would be an issue for HA, but if coverage would be good to have for HA it could be prioritized.

**Comment by addyosmani** [comment]
> If we add the v8 runtime stats trace events (disabled-by-default-v8.runtime_stats) we can get more granular details but it adds some overhead.

If we could could get V8 Runtime Call Stats (RCS) in there, it'd be nice. Would expose the more granular details like accurate parse times, GC etc. It's unclear to me how HA/WPT decide on the value of the overhead, but from an analysis POV I'd found them valuable.

If we can't use RCS, the parse/eval/compile stats from Rick would be a good stop-gap. I'd echo the comment about not double-counting - we should probably go for these or RCS.

**Comment by paulirish** [comment]
`disabled-by-default-v8.runtime_stats_sampling` is low enough overhead to include, iirc. @a1ph to confirm

**Comment by igrigorik** [comment]
Sounds like the resolutions here are:

1. enable `v8.runtime_stats_sampling` in HA. 
1. we're waiting for code coverage audits to land in LH

Does that sound right?  

@pmeenan @rviscomi can we enable 1?
@addyosmani do we have a bug for code coverage that we can track?

**Comment by a1ph** [comment]
disabled-by-default-v8.runtime_stats_sampling does not turn the sampling itself. It just enables V8 RCS pseudo stack collection. The sampling is enabled by v8.cpu_profiler and v8.cpu_profiler.hi_res

**Comment by pmeenan** [comment]
I'd need to do the work to enable the profiler and parse the profiler results into higher-level stats.  I can probably take a look at it later this week but I also need to run some tests to make sure the added time to running the test is minimal because we are REALLY close to the edge on our capacity.

**Comment by addyosmani** [comment]
@igrigorik I'll defer to @patrickhulce as he worked on JS code coverage support in Lighthouse last and may have a new PR we can follow along with sometime shortly.

**Comment by patrickhulce** [comment]
For JS coverage the relevant LH tracking bug is https://github.com/GoogleChrome/lighthouse/issues/1852 and a PR to follow will be opened once https://github.com/GoogleChrome/lighthouse/pull/2518 is merged.

**Comment by igrigorik** [comment]
@patrickhulce @addyosmani cool, thanks guys!

**Comment by igrigorik** [comment]
> I'd need to do the work to enable the profiler and parse the profiler results into higher-level stats. I can probably take a look at it later this week but I also need to run some tests to make sure the added time to running the test is minimal because we are REALLY close to the edge on our capacity.

@pmeenan any updates or findings on this one?

**Comment by igrigorik** [comment]
JS coverage audit landed: https://github.com/GoogleChrome/lighthouse/issues/1852#event-1227935261 ... \o/

**Comment by rviscomi** [comment]
Tracking remaining issues here https://github.com/HTTPArchive/httparchive.org/issues
