### ISSUE TITLE
New report: Progressive Web Apps

### ISSUE THREAD

**Issue by addyosmani** [HTTPArchive/legacy.httparchive.org#126]
**Metrics:** 
Lighthouse score, (from @igrigorik) pass/fail ratios for each sub-audit to get a sense for where the bottlenecks are. Should all of the sub-audits be included? list of the initial ones below.

**Source:** WebPageTest Lighthouse reports

**Visualization:** time-series charts similar to http://beta.httparchive.org/reports/js

**URL:** http://beta.httparchive.org/reports/pwa

![image](https://user-images.githubusercontent.com/110953/28740889-0f0bb0d6-73c0-11e7-83a7-779fba358919.png)

**Comment by rviscomi** [comment]
See https://httparchive.org/reports/progressive-web-apps
