### ISSUE TITLE
UI fixes for harviewer

### ISSUE THREAD

**Issue by stevesouders** [HTTPArchive/legacy.httparchive.org#13]
Brian Pane made significant improvements to harviewer in  bug #194 . But now he's starting at Facebook (!) and won't be able to work on these fixes for awhile. So I'm creating a separate bug with the remaining issues:

Looks good. I pushed to production, for example:
    http://httparchive.org/viewsite.php?pageid=370857#waterfall

Here are some issues. Items 5-10 could be broken out into (a) separate bug(s). Perhaps some of them could be tackled in an update to this bug, and the bigger, less important ones broken out into new bugs.
1. The popup menu that appears when you click the down arrow at the far right of a horizontal bar is not positioned correctly. It shows up in the upper right of the browser's window, instead of under the down arrow.
2. When you expand a request row and look at the "Headers" tab the rows are not aligned correctly. They're too tall and vertical-align is different. It appears this comes from requestBody.css (eg, .netInfoParamName { vertical-align: top }. (see attached screenshot)
3. The gray shading at the top of an expanded row is not aligned (see attached screenshot). If I expand a request row, there's a TD that has class="tabViewCol" with a background url "timeline-sprites.png". The tavViewCol TD is inside another TD with class=netInfoCol with the same bg sprite. The problem is the tavViewCol TD is _wider_ than the netInfoCol TD, so the two gray sprite bgs are different widths and don't align. 
4. The colored bars in the legend of the connection state popup are outside of the popup box. (This is the popup you see when you hover over a horizontal time bar.)
5. Let's get rid of the word "GET" in each row.
6. As you mention, need to get rid of the STATUS column and use colors.
7. Please add the Content-Type column. For now, just show one uppercase letter per this key: HTML (H), JavaScript (J), CSS (C), Images (I), Flash (F), all other text/\* (XML, JSON, etc.) (T), other (O). I hope to have actual columns w/in a week that are basically these letters (perhaps slightly modified) with a colored background where the color is also keyed off the content-type.
8. Do we intentionally not have a Response tab when you expand a request row?
9. I'd like to show the images when you hover just like Net Panel. The image will be fetched when the user hovers. The issue is - the image may no longer exist (eg, we did the run 6 months ago) OR the image has been modified since we did the run so the image shown today is NOT what was fetched previously. Despite these issues, I'd still like to do this. 
10. I notice Firebug Net Panel has a Cache tab when you expand a request row. We could supply Date, Last Modified, Expires, Data Size, Cache-Control, and ETag. I could see this getting VERY tricky given the boundary between the HTTP Archive code and the HarViewer code, but if we could do it it would be nice. All of this info is in the table lower in the page.

**Comment by igrigorik** [comment]
@pmeenan curious, is it possible to extract/embed WPT's waterfall? Instead of rebuilding a copy of it here...

**Comment by rviscomi** [comment]
Closing as obsolete. Feel free to reopen if there is still interest in this.
