### ISSUE TITLE
Set up an SSL cert for httparchive.org

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/legacy.httparchive.org#132]
I hear that HTTPS thing is getting popular.

**Comment by pmeenan** [comment]
I've set up lets-encrypt on WPT and it should be easy enough to do on HA with the nginx support.  Only complication is the nginx server reverse-proxies the HA requests to an apache server so not sure if the webroot will "just work" or if it will need a few tweaks.

**Comment by rviscomi** [comment]
I just gave certbot a whirl and it failed to download a bunch of dependencies, which I think is a symptom of our version of Ubuntu being old.

The beta site is hosted on App Engine and the current site will become old.httparchive.org or something, so maybe it makes more sense to wait for the musical subdomains to settle down before setting up certs.

**Comment by igrigorik** [comment]
Yeah, I'd focus on HTTPS for the new (GAE-powered) site, with a view that we want to sunset current site asap -- lack of HTTPS being one of many reasons.

**Comment by rviscomi** [comment]
TODO:

- [ ] migrate the beta site from its own GAE project to the primary `httparchive` project
- [ ] set up a wildcard cert for GAE-hosted sites, to support the beta site in both dev (beta.httparchive.org) and prod (httparchive.org) stages

**Comment by rviscomi** [comment]
TODO(self): Need to confirm that the cert for the beta subdomain will work when it becomes the primary domain. If so this issue is ok to close.

**Comment by pmeenan** [comment]
The legacy server is https now (httparchive.org, www, dev, desktop, mobile, chrome)

**Comment by rviscomi** [comment]
Pat, I set up a new A record for `legacy.httparchive.org`. Is the https cert a wildcard?

**Comment by pmeenan** [comment]
No.  Should be able to be added with certbot (I'll do it on Monday)

**Comment by pmeenan** [comment]
Cert has been expanded
