### ISSUE TITLE
reduce bulktest errors

### ISSUE THREAD

**Issue by stevesouders** [HTTPArchive/legacy.httparchive.org#14]
https://code.google.com/p/httparchive/issues/detail?id=250

~5% of tests fail. Figure out why. Start recording "failed" in the archive so people know WHY there are no results for a given crawl. Use that history to remove URLs that constantly fail.

**Comment by stevesouders** [comment]
Some notes: The "urls" table has some helpful columns like "optout" and "urlFixed". These could be used to address this bug. For example, 
  - If the Alexa zip file contains a domain that no longer exists, you could set optout=true in the urls table and it will no longer be tested
  - if our HA code is INcorrectly converted a domain to http://www.foo.com and that produces an error but http://foo.com works, then you could set urlFixed to http://foo.com and I believe the crawl code already prefers urlFixed and then falls back to urlOrig

**Comment by Themanwithoutaplan** [comment]
Not sure if this is directly related but I picked up really a couple of minor errors with the September 1st run (both mobile and desktop). A couple of sites have `NULL` `numDomains` which is a constraint violation when I import them into Postgres and I think this constraint is correct, hence these are errors.

```
DETAIL: Failing row contains (3448296, 1473341436, All, Sep 1 2016, , 0, http://www.mc361.com/, 1473336845, 12088, 11430, 36559, null, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, 2016-09-01, 4576, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2226, 0, 0, 0, 0, 0, 0, 0, 38050, null, 14523, 40100, 221861, 7247, null, null, 454, null, ).
CONTEXT: COPY urls, line 3868: "3448296	1473341436     	All    	Sep 1 2016     	454    		0      	http://www.mc361.com/  	\N     	1473336845     	4576   	12088  	11430  	36559  	..."
2016-09-12T18:05:11.142000+02:00 ERROR Database error 23502: null value in column "numDomains" violates not-null constraint
DETAIL: Failing row contains (3448299, 1473341436, All, Sep 1 2016, , 0, http://www.kurogal.com/, 1473337075, 12192, 19818, 25634, null, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, 2016-09-01, 8366, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1305, 0, 0, 0, 0, 0, 0, 0, 27839, null, 20503, 26100, 361553, 19184, null, null, 454, null, width=device-width, initial-scale=1.0, maximum-scale=1.0).
CONTEXT: COPY urls, line 3: "3448299   	1473341436     	All    	Sep 1 2016     	454    		0      	http://www.kurogal.com/	\N     	1473337075     	8366   	12192  	19818  	2563..."
2016-09-12T18:05:11.548000+02:00 ERROR Database error 23502: null value in column "numDomains" violates not-null constraint
DETAIL: Failing row contains (3448300, 1473341437, All, Sep 1 2016, , 0, http://www.digitalsummit.com/, 1473336869, 7662, 4288, 25830, null, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, 2016-09-01, 2059, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 488, 0, 0, 0, 0, 0, 0, 0, 33855, null, 8677, 11400, 1289606, 81990, null, null, 454, null, width=device-width, initial-scale=1, maximum-scale=1).
CONTEXT: COPY urls, line 1: "3448300   	1473341437     	All    	Sep 1 2016     	454    		0      	http://www.digitalsummit.com/  	\N     	1473336869     	2059   	7662   	4288   	..."
```

**Comment by rviscomi** [comment]
Closing as obsolete. Feel free to reopen if there is still interest in this.

FYI the error rate is lower now that we are using the CrUX corpus.
