### ISSUE TITLE
Crawlid 558 missing from stats

### ISSUE THREAD

**Issue by Themanwithoutaplan** [HTTPArchive/legacy.httparchive.org#150]
The mobile crawls for 15th July 2018 has crawlids of 558 and 559 but the dump of the stats table has 557 and 559 but no 558 so a join isn't possible.
Which table is correct?

**Comment by rviscomi** [comment]
We had to restart the mobile crawl, so 559 should be correct.

**Comment by Themanwithoutaplan** [comment]
Thanks for the quick reply. Any chance of the 558s being stripped from the downloads? If necssary I can probably create the files myself.

**Comment by rviscomi** [comment]
We're trying not to muck with the legacy test server logic so closing this issue for now.
