### ISSUE TITLE
Data from 2018-12-15 contains duplicate tests for some sites

### ISSUE THREAD

**Issue by Themanwithoutaplan** [HTTPArchive/legacy.httparchive.org#155]
I'm not sure quite of the details yet but it looks to me that it affects quite a few sites. I don't see any additional crawls. Am I missing something? Or is this a known issue?

**Comment by rviscomi** [comment]
Thanks for reporting this. Can you give an example of the issue you're seeing (eg a query that produces duplicate results)?

**Comment by Themanwithoutaplan** [comment]
Hi Rick, working on the query at the moment… Using the MySQL schema something like the following should give you an indication. 
```
select url, count(url) as ct from pages
where label = 'Dec 15 2018'
group by url
order by ct desc
having count(url) > 2 -- desktop and mobile
```
As I have a slightly modified schema I can't run this directly and I've no idea how to do this in big table.

**Comment by Themanwithoutaplan** [comment]
Oh, I thought I'd posted a list of URLs. Can't get the hang of GitHub's attachment thang. In any case seeing the same problem with the January results. Will try and post a list here. Was about 100,000 sites in for December 15th and affected both desktop and mobile crawls.

**Comment by rviscomi** [comment]
I think this is a similar issue to https://github.com/HTTPArchive/legacy.httparchive.org/issues/156 where we had to restart the crawl for some reason. I think we have it under control now so this shouldn't affect future crawls.
