### ISSUE TITLE
Calculation of reqTotal incorrect for many sites for 2019-03-01 data

### ISSUE THREAD

**Issue by Themanwithoutaplan** [HTTPArchive/legacy.httparchive.org#157]
I came across this for one site:
https://legacy.httparchive.org/viewsite.php?pageid=118534738

And then ran a query of the dataset and it seems to affect a huge number of sites (3,281,322 in total). As there is a waterfall for the site, it looks like something went wrong calculating the statistics for the run. Maybe they can be recalculated? Not sure if it affects other runs.

**Comment by rviscomi** [comment]
This is due to a known data loss issue. See https://github.com/HTTPArchive/httparchive.org/issues/135
