### ISSUE TITLE
Legacy website not reachable

### ISSUE THREAD

**Issue by Themanwithoutaplan** [HTTPArchive/legacy.httparchive.org#161]
Currently cannot access the site to get the data downloads.

**Comment by pmeenan** [comment]
Probably related to
https://twitter.com/internetarchive/status/1143378990826004480?s=21

**Comment by Themanwithoutaplan** [comment]
Looks like it. Thanks, Pat.
http://currentlydown.com/archive.org

**Comment by rviscomi** [comment]
Closing this issue, as there's nothing we can do.

**Comment by pmeenan** [comment]
FWIW, connectivity has been restored.
