### ISSUE TITLE
A11Y metrics bugs

### ISSUE THREAD

**Issue by obto** [HTTPArchive/legacy.httparchive.org#187]
Running list of bugs encountered while processing the data

1. `total_elements_with_non_empty_alt` is never incremented in the for loop. because of this, it is always 0. We can still get all the data we need. Just have to parse `_almanac` as well
https://github.com/HTTPArchive/legacy.httparchive.org/blob/0b19588815d0fd869a6145670c29d257196ac17b/custom_metrics/a11y.js#L83-L103

**Comment by Tiggerito** [comment]
My markup custom metric gathers this, which may be of help. Present = non blank/empty. Not verified it yet.
```
"images": {
        "img": {
            "total": 9,
            "alt": {
                "missing": 2,
                "blank": 5,
                "present": 2
            }
        }
    },
```

**Comment by rviscomi** [comment]
@obto are you able to make a PR with this fix?

**Comment by obto** [comment]
Yeah for sure
