### ISSUE TITLE
wpt_bodies meta description and robots gathering is invalid as the selector used is case sensitive

### ISSUE THREAD

**Issue by Tiggerito** [HTTPArchive/legacy.httparchive.org#188]
https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/wpt_bodies.js

It seems that name attribute values are case sensitive, so this line will only get a subset of meta descriptions.

`target.total = [...d.querySelectorAll('head meta[name="description"]')].map(e => {`

The line should be:

`target.total = [...d.querySelectorAll('head meta[name="description"i]')].map(e => {`

Same goes for the selectors in the calculateAllRobots function.

**Comment by rviscomi** [comment]
Fixed by https://github.com/HTTPArchive/legacy.httparchive.org/pull/189
