### ISSUE TITLE
use "median" instead of finding median run

### ISSUE THREAD

**Issue by stevesouders** [HTTPArchive/legacy.httparchive.org#20]
WPT now has the ability for using "median" instead of the actual median run # for URLs like:

filmstrip: http://httparchive.webpagetest.org/video/compare.php?tests=140515_0_9SC-r:1-c:0

details: http://httparchive.webpagetest.org/result/140515_0_9SC/1/details/

Let's simplify the HA code and use this.

**Comment by rviscomi** [comment]
Closing as obsolete. We've reduced the number of runs per test to 1.
