### ISSUE TITLE
Stat Suggestion: Mobile Comparison

### ISSUE THREAD

**Issue by estelle** [HTTPArchive/legacy.httparchive.org#38]
It would be great to see stats for the top 1000 for mobile versus desktop: either via media queries (wide screen v narrow screen), user agent (mobile v desktop) and/or mobile site via redirect (www. v m.)

**Comment by vijayachetlapalli** [comment]
Is this stat available?

**Comment by stevesouders** [comment]
Indeed, comparing crawls would be a nice new feature. This is a big effort and not currently scheduled.

**Comment by rviscomi** [comment]
This is something we hope to support in https://github.com/HTTPArchive/httparchive/issues/81

**Comment by igrigorik** [comment]
Can we close and merge this into #81?

**Comment by rviscomi** [comment]
Fixed by #81
