### ISSUE TITLE
Drill into example sites from the summary metrics

### ISSUE THREAD

**Issue by LeslieMurphy** [HTTPArchive/legacy.httparchive.org#63]
For example, drill into sites that have more than 3 URL redirects, by clicking on the chart
![redirects per page](https://cloud.githubusercontent.com/assets/4464416/14614272/9cf2ddac-055d-11e6-88b7-c6562ae64654.png)

**Comment by rviscomi** [comment]
Closing as obsolete. Feel free to reopen if there is still interest in this.
