### ISSUE TITLE
Chrome runs potentially contains more errors in renderStart than IE

### ISSUE THREAD

**Issue by Themanwithoutaplan** [HTTPArchive/legacy.httparchive.org#70]
I've recently noticed a few sites reporting `renderStart` as 0 while containing other timing data. I've just run a check over several months and it looks like the Chrome runs have about 10 times as many such incidents as IE for the same reporting period, at around 5% of all sites.

This is what I'm seeing:

| label | browser | count |
| --- | --- | --- |
| 2016-06-15 | Chrome | 32741 |
| 2016-06-15 | IE | 2652 |
| 2016-06-01 | Chrome | 26724 |
| 2016-06-01 | IE | 2331 |
| 2016-05-15 | Chrome | 21829 |
| 2016-05-15 | IE | 2227 |
| 2016-05-01 | Chrome | 30211 |
| 2016-05-01 | IE | 2153 |
| 2016-04-15 | Chrome | 30082 |
| 2016-04-15 | IE | 2736 |
| 2016-04-01 | Chrome | 33659 |
| 2016-04-01 | IE | 2348 |
| 2016-03-15 | Chrome | 33904 |
| 2016-03-15 | IE | 2193 |
| 2016-03-01 | Chrome | 32629 |
| 2016-03-01 | IE | 2078 |
| 2016-02-15 | Chrome | 11621 |
| 2016-02-15 | IE | 2040 |
| 2016-02-01 | Chrome | 11428 |
| 2016-02-01 | IE | 2078 |
| 2016-01-15 | Chrome | 11515 |
| 2016-01-15 | IE | 2053 |
| 2016-01-01 | Chrome | 11831 |
| 2016-01-01 | IE | 1966 |
| 2015-12-15 | Chrome | 12359 |
| 2015-12-15 | IE | 2188 |
| 2015-12-01 | Chrome | 29811 |
| 2015-12-01 | IE | 2213 |
| 2015-11-15 | Chrome | 29356 |
| 2015-11-15 | IE | 2153 |
| 2015-11-01 | Chrome | 29589 |

**Comment by pmeenan** [comment]
Do you have the overall test counts that do have renderStart?  The overall reported success rate for the Chrome crawls is higher than the IE crawls so I'm wondering if certain tests are just not being reported as failures.  Looking at the last crawl, it looks like there was only a 2% failure rate (which includes pages that are down, etc) which is somewhat lower than I remember the IE crawls showing.

**Comment by Themanwithoutaplan** [comment]
You mean where `renderStart` > 0? Well, that would be run size - above. But I don't know if these are are test failures. I usually only look at `renderStart` and `onLoad` and in the sites I was looking at `onLoad` was not 0.

This is number of cases where both are 0 so it looks the problem is with `renderStart` for some reason. I can provide a list of test ids if that helps.

   label    | browser | count
------------|---------|-------
 2015-12-01 | Chrome  |     5
 2015-11-15 | Chrome  |     7
 2015-11-01 | Chrome  |     1

**Comment by pmeenan** [comment]
The target crawl size is on the order of 500,000 pages but it's not unusual to have failures for 5-8% of those and the detected failures may not be in the data set.  Maybe put another way, what are the run sizes that you are seeing for IE and Chrome?

**Comment by Themanwithoutaplan** [comment]
This is an analysis of the public desktop runs, so ~500,000. Again AFAIK these are not test failures but runs with incomplete results.

BTW. what's up with the site at the moment? discuss.httparchive.org isn't resolving at the moment.

**Comment by igrigorik** [comment]
On Sun, Jun 26, 2016 at 8:19 AM, Themanwithoutaplan <
notifications@github.com> wrote:

> BTW. what's up with the site at the moment? discuss.httparchive.org isn't
> resolving at the moment.
>
Doh. We migrated the domain to the new registrar, looks like CNAME record
got lost in the move. Fixed.

**Comment by Themanwithoutaplan** [comment]
@igrigorik thanks. BTW what's the e-mail for the service? The e-mails I receive have a reply-to that doesn't work.

**Comment by igrigorik** [comment]
You mean on discuss.httparchive.org? Those seem to work for me.. I'll take a look.

**Comment by Themanwithoutaplan** [comment]
Things like `topic/756@discuss.httparchive.org` and `info@httparchive.org`.

**Comment by igrigorik** [comment]
Digging into the data with @souders.. 

It looks like most of these cases are due to [error 12029](https://github.com/WPO-Foundation/webpagetest/search?q=12029) (failed resolve or connect). The firstRender for these is 0 but we do show other metrics, which is super confusing.

We should probably omit such entries, but before we get to that.. We should figure out why we're seeing such a big increase in failed navigations / socket timeouts?

**Comment by stevesouders** [comment]
Here's some pageids & wptids:
| 66859423 | 160801_0_4  |           0 |    238 |
| 66859427 | 160801_0_A  |           0 |    226 |
| 66859430 | 160801_0_F  |           0 |    257 |
| 66859431 | 160801_0_E  |           0 |    272 |
| 66859434 | 160801_0_K  |           0 |    395 |
| 66859442 | 160801_0_B  |           0 |    300 |
| 66859474 | 160801_0_24 |           0 |    284 |
| 66859483 | 160801_0_22 |           0 |    248 |
| 66859487 | 160801_0_2R |           0 |    324 |
| 66859495 | 160801_0_3H |           0 |    239 |

**Comment by stevesouders** [comment]
There are two issues:

1. We are NOT supposed to store error results in the "pages" table - we only store successful results. Many (most? all?) of these with renderStart = 0 are errors - so we need to get them OUT of the "pages" table.

2. Why are so many erroring out?

**Comment by stevesouders** [comment]
I tried the first URL I found and sure enough it's a bad hostname: http://www.orkut.co.in/

**Comment by igrigorik** [comment]
Related bug: https://github.com/HTTPArchive/httparchive/issues/14

**Comment by rviscomi** [comment]
Closing as obsolete. Feel free to reopen if there is still interest in this.
