### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/legacy.httparchive.org#79]
Document the development and maintenance flow. Use prosaic text, diagrams, and inline comments as necessary.

Open questions:
- In what format do we write the docs: Markdown? HTML? Plain text?
- Where do the docs live: /docs dir? Google Docs? Adjacent to code?
- Do we surface the docs on the web interface? How?
- What are the high priority things to document?
- What is the process for updating docs?

**Comment by rviscomi** [comment]
> In what format do we write the docs: Markdown? HTML? Plain text?
> Where do the docs live: /docs dir? Google Docs? Adjacent to code?
> Do we surface the docs on the web interface? How?

These three are tightly connected.

One idea is to create markdown files in a /docs subdirectory and create a build rule for generating a web-friendly docs site in HTML.

**Comment by pmeenan** [comment]
Also need to separate out things that are generic for any httparchive install (if people are still running them) vs anything that is specific to the httparchive.org instance

**Comment by igrigorik** [comment]
FWIW, I'm not aware of anyone running this on their own. I don't think we should discourage that (it is open source), but I don't think that should be our goal either. For example, we'll be moving a lot of our processing away from MySQL to BigQuery..

> In what format do we write the docs: Markdown? HTML? Plain text?
> Where do the docs live: /docs dir? Google Docs? Adjacent to code?
> Do we surface the docs on the web interface? How?

My vote is for markdown, as it's easy to author and maintain. To start, I'd propose we create /docs and put everything there. Longer term, I'd love to see these docs visible on httparchive.org/about/{something}.. we can move MD files once we have the new design.

**Comment by rviscomi** [comment]
Working on a draft of a doc on the HA data pipeline. Will check it in as .md when ready, but would appreciate comments/edits to help fill in the blanks or make corrections.

https://docs.google.com/document/d/1z18KGAJZ0i4WCYF06nlvuT5_284Idt1_JIYMb3JLSXg/edit?usp=sharing

**Comment by igrigorik** [comment]
Nice! Great start, looking forward to fleshing it out.

**Comment by rviscomi** [comment]
@paulcalvano is going to work on adding an "Getting Started with BigQuery" doc. (Can't assign to him for some reason 😭).

**Comment by igrigorik** [comment]
I think Paul needs to be a member of the org..

**Comment by rviscomi** [comment]
He is! :sob: :sob:

**Comment by paulcalvano** [comment]
Thanks!   I started writing the documentation here.   Let me know if this format is OK.   https://github.com/paulcalvano/httparchive/blob/master/docs/bigquery-gettingstarted.md

**Comment by paulcalvano** [comment]
OK - I finished writing up the first draft.   Please review and let me know if you'd like me to change anything.

**Comment by rviscomi** [comment]
See https://github.com/HTTPArchive/httparchive.org/tree/master/docs
