### ISSUE TITLE
Track third party JS library vulnerabilities

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/legacy.httparchive.org#84]
As an extension of the FR in https://github.com/HTTPArchive/httparchive/issues/77, the JS library data can be joined with vulnerability data. See https://github.com/snyk/vulnerabilitydb and https://github.com/RetireJS/retire.js.

Some questions this can answer:
- are popular websites more secure?
- what does the vulnerability distribution look like? across different severity levels?
- what are the most prolific libraries that have vulnerabilities?
- which websites share common vulnerabilities?

And by extension:
- are any CMS platforms generating insecure websites?

Ideally, this data would be used by white hats to understand the security landscape on the web and help developers make more secure websites. There would be some kind of process for proactively alerting site owners about their vulnerabilities, or at least making it easy for them to get an audit of their site.

/cc @tlauinger @guypod @tkadlec @igrigorik @ebidel https://github.com/GoogleChrome/lighthouse/issues/1948

**Comment by igrigorik** [comment]
How/where does retire.js source vulnerability data? Or, put differently, what are the pros and cons of using snyk DB approach vs retire.js?

**Comment by tlauinger** [comment]
Retire.js has its own DB that is manually put together by volunteers from a range of public sources. Actually, there are two - one for client-side JS libraries, and another for Node packages. Snyk only has Node packages.

When we started our research project, we looked into getting package metadata from the NPM repository, but we found that some client-side JS libraries either aren't in NPM at all, or NPM doesn't have older versions since many libraries already existed before NPM was a thing. In conclusion, I think vulnerability data about Node packages can be a useful addition, but I wouldn't use it as the sole source of client-side vulnerabilities.

**Comment by igrigorik** [comment]
> Snyk only has Node packages.

@guypod @tkadlec I do see JQuery and other client-side libs in your db. Where/how are these lists of vulnerabilities sourced?

**Comment by guypod** [comment]
Snyk does capture many client side libraries too, not just Node packages. These packages exist in npm too, which as you know is used regularly in front end dev. 

Our tools test for those libraries only when fetched from npm, as we don't currently have the code to inventory libraries from the web page itself. Doing so accurately is it's own challenge, and we have some ideas we can share there but we haven't completed it.

If you're already building the inventorying into lighthouse or webpagetest, our DB should be a comprehensive source of these vulnerabilities, and give users good metadata and fix instructions for the issues they find. Will be happy to test out pages if you spot any gaps with this statement!

Using multiple sources is not a bad idea, though I don't think retire.js is a DB. It's a detection tool, referring to other DBs as the sources, so wouldn't that be redundant with the inventorying tech you build here?

**Comment by rviscomi** [comment]
On the subject of integration, [LibraryDetector](https://github.com/johnmichel/Library-Detector-for-Chrome/blob/master/library/libraries.js) uses long-form strings like `"Google Maps"` to identify the detected libraries, while Snyk identifies from GH repo or npm name. I'm not even sure if the Maps API is open source and Snykable. I see https://snyk.io/test/github/googlemaps/google-maps-services-js but that's the nodejs library.

So we'd probably also need to map LibraryDetector names to Snyk-compatible repos/packages if available.
